classrooms/urls.py
from django.urls import path
from . import views
from . import fetchviews


urlpatterns = [
    path('classrooms/',
         views.ClassroomListView.as_view(), name='classrooms'),
    path('classroom/create-new/',
         views.ClassroomCreateView.as_view(), name='class-create'),
    path('classroom/<str:pk>/',
         views.ClassroomDetailView.as_view(), name='class-details'),
    path('classroom/<str:pk>/edit/',
         views.ClassroomUpdateView.as_view(), name='class-update'),
    path('classroom/<str:pk>/delete/',
         views.ClassroomDeleteView.as_view(), name='class-delete'),
    path('classroom/<str:pk>/post/create-new/',
         views.PostCreateView.as_view(), name='post-new'),
    path('classroom/<str:class_pk>/post/<str:pk>/',
         views.PostDetailView.as_view(), name='post-details'),
    path('classroom/<str:class_pk>/post/<str:pk>/update/',
         views.PostUpdateView.as_view(), name='post-update'),
    path('classroom/<str:class_pk>/post/<str:pk>/delete/',
         views.PostDeleteView.as_view(), name='post-delete'),
    path('classroom/<str:class_pk>/assignment/create-new/',
         views.AssignmentCreateView.as_view(), name='assignment-new'),
    path('classroom/<str:class_name>/assignment/<str:pk>/',
         views.assignment_detail_view, name='assignment-details'),
    path('classroom/<str:class_name>/assignment/<str:pk>/update/',
         views.AssignmentUpdateView.as_view(), name='assignment-update'),
    path('classroom/<str:class_name>/assignment/<str:pk>/delete/',
         views.AssignmentDeleteView.as_view(), name='assignment-delete'),
    path('classroom/<str:class_name>/assignment/<str:pk>/unsubmit/'
         '', views.assignment_unsubmit_view, name='assignment-unsubmit'),
    path('classroom/<str:class_name>/assignment/<str:assignment_pk>/submission-details/',
         views.assignment_submissions_view, name='submit-details'),
    path('complete-review/<str:assignment_pk>/',
         views.assignment_complete_review_view, name='complete-review'),
    path('undo-complete-review/<str:assignment_pk>/',
         views.assignment_undo_complete_review_view, name='undo-review-complete'),
    path('assignments/all/<str:type>/',
         views.AssignmentListView.as_view(), name='assignments-list'),

    # Quizzes Urls
    path('quizzes/<str:type>/',
         views.QuizListView.as_view(), name='quiz-list'),
    path('classroom/<str:pk>/quiz/create-new/',
         views.QuizCreateView.as_view(), name='quiz-create'),
    path('classroom/<str:class_name>/quiz/<str:pk>/details/',
         views.QuizDetailView.as_view(), name='quiz-details'),
    path('classroom/<str:class_name>/quiz/<str:pk>/delete/',
         views.QuizDeleteView.as_view(), name='quiz-delete'),
    path('classroom/<str:class_name>/quiz/<str:pk>/edit/',
         views.QuizUpdateView.as_view(), name='quiz-update'),

    # Quiz question url
    path('classroom/<str:class_name>/quiz/<str:quiz_pk>/questions/',
         views.quiz_questions_and_answers_view, name='quiz-questions'),
    path('classroom/<str:class_name>/quiz/<str:quiz_pk>/live',
         views.quiz_live_view, name='quiz-live'),

    # Quiz response details page made by a student
    path('classroom/<str:class_name>/quiz/<str:quiz_pk>/response',
         views.quiz_stu_response_view, name='quiz-response'),

    # Quiz results page (for lecturer)
    path('classroom/<str:class_name>/quiz/<str:quiz_pk>/results',
         views.QuizResultsView.as_view(), name='quiz-results'),

    # Other fetch views
    path('classroom/<str:class_name>/quiz/<str:quiz_pk>/countdown',
         fetchviews.quiz_start_time_view, name='quiz-countdown'),


    # Meeting Urls
    path('meetings/<str:type>/',
         views.MeetingListView.as_view(), name='meetings-list'),
    path('classroom/<str:pk>/meeting/create-new/',
         views.MeetingCreateView.as_view(), name='meeting-create'),
    path('classroom/<str:class_name>/meeting/<str:pk>/details/',
         views.MeetingDetailView.as_view(), name='meeting-details'),
    path('classroom/<str:class_name>/meeting/<str:pk>/delete/',
         views.MeetingDeleteView.as_view(), name='meeting-delete'),
    path('classroom/<str:class_name>/meeting/<str:pk>/edit/',
         views.MeetingUpdateView.as_view(), name='meeting-update'),
]

django_LMS/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('', include('users.urls')),
    path('', include('classrooms.urls')),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

main/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name="home"),
    path('events-today/', views.today_events, name='events-today'),

]

classrooms/models.py
import os.path
from datetime import datetime, timedelta
from django.db import models
from users.models import CustomizedUser, Student, Lecturer
from main.models import Batch, Department
from ckeditor.fields import RichTextField
from main.funcs import (
    local_to_utc_aware,
    local_to_utc_naive,
    utc_to_local_aware,
    utc_to_local_naive,
    get_naive_dt
)


class Classroom(models.Model):
    owner = models.ForeignKey(Lecturer, on_delete=models.CASCADE, related_name='owner')
    department = models.ForeignKey(Department, on_delete=models.CASCADE)
    lecturers = models.ManyToManyField(Lecturer)
    name = models.CharField(max_length=300)
    description = models.TextField(max_length=150, null=True,  blank=True)
    background_img = models.ImageField(null=True, blank=True)
    date_created = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = (('department', 'name'),)

    def __str__(self):
        return f"Class: {self.name} [{self.department}]"


class Post(models.Model):
    classroom = models.ForeignKey(Classroom, on_delete=models.CASCADE)
    owner = models.ForeignKey(Lecturer, on_delete=models.CASCADE)
    title = models.CharField(max_length=300)
    _date_created = models.DateTimeField(auto_now_add=True)
    date_last_mod = models.DateTimeField(auto_now=True)
    content = RichTextField(blank=True, null=True)

    class Meta:
        unique_together = (('classroom', 'title'),)

    @property
    def date_created(self):
        return get_naive_dt(self._date_created)

    def __str__(self):
        return f"Post: {self.title} [{self.classroom}]"


"""
=================================
    ASSIGNMENT
=================================
"""


class Assignment(models.Model):
    classroom = models.ForeignKey(Classroom, on_delete=models.CASCADE)
    owner = models.ForeignKey(Lecturer, on_delete=models.CASCADE)
    type = models.CharField(max_length=8, default='regular',
                            choices=[('regular', 'Regular'),
                                     ('question', 'Question')])
    title = models.CharField(max_length=300)
    _date_created = models.DateTimeField(auto_now_add=True)
    _date_last_mod = models.DateTimeField(auto_now=True)
    _date_due = models.DateTimeField()
    content = RichTextField()   # From CK Editor
    file = models.FileField(null=True, blank=True, upload_to='assignment-files')  # This won't be used actually
    review_complete = models.BooleanField(default=False)

    class Meta:
        unique_together = (('title', 'classroom'),)

    def __str__(self):
        return f"Assignment: {self.title} [ {self.classroom} ]"

    @property
    def type(self):
        return "assignment"

    @property
    def date_created(self):
        return utc_to_local_naive(self._date_created)

    @property
    def date_due(self):
        return utc_to_local_naive(self._date_due)

    @property
    def date_mod(self):
        return utc_to_local_naive(self._date_last_mod)

    @property
    def expired(self):
        if get_naive_dt(self.date_due) < get_naive_dt(datetime.utcnow()):
            return True
        return False

    @property
    def pending_submissions(self) -> int:
        _all_stu = self.classroom.department.student_set.count()
        _all_sub_done = self.submission_set.count()
        pending = int(_all_stu) - int(_all_sub_done)
        return pending


class Submission(models.Model):
    assignment = models.ForeignKey(Assignment, on_delete=models.CASCADE)
    owner = models.ForeignKey(Student, on_delete=models.CASCADE)
    _date_created = models.DateTimeField(auto_now_add=True)
    grade = models.CharField(max_length=20, null=True, blank=True)
    file = models.FileField(blank=True, null=True)  # this should not be saved. instead, <SubmissionFile> will be used.
    lec_comment = models.TextField(null=True, blank=True)

    def __str__(self):
        return f"Submission By: {self.owner.user.username}" \
               f" [Assignment-> {self.assignment.title}]"

    @property
    def date_created(self):
        return utc_to_local_naive(self._date_created)

    @property
    def is_late_submit(self):
        """
        If the submission is a late submit or not.
        :return:
        """
        if self.date_created > self.assignment.date_due:
            return True
        return False


class SubmissionFile(models.Model):
    """
    Used for multiple file upload functionality
    """
    submission = models.ForeignKey(Submission, on_delete=models.CASCADE)
    file = models.FileField(upload_to='submission-files')

    def get_short_file_name(self):
        name = self.file.name
        return os.path.basename(name)[-28:]


"""
=================================
    MEETING
=================================
"""


class Meeting(models.Model):
    classroom = models.ForeignKey(Classroom, on_delete=models.CASCADE)
    owner = models.ForeignKey(Lecturer, on_delete=models.CASCADE)
    topic = models.CharField(max_length=300)
    _date_created = models.DateTimeField(auto_now_add=True)
    _date_mod = models.DateTimeField(auto_now=True)
    _start = models.DateTimeField()
    description = models.TextField(null=True, blank=True)
    meeting_url = models.URLField(null=True, blank=True)
    meeting_id = models.CharField(null=True, blank=True, max_length=300)
    meeting_pwd = models.CharField(null=True, blank=True, max_length=200)
    recording_url = models.URLField(null=True, blank=True)

    class Meta:
        unique_together = (('classroom', 'topic'),)

    def __str__(self):
        return f"Meeting: {self.topic} [Class-> {self.classroom.name}" \
               f" {self.classroom.department.batch.year} Batch]"

    @property
    def type(self):
        return 'meeting'

    @property
    def date_created(self):
        return utc_to_local_naive(self._date_created)

    @property
    def date_mod(self):
        return utc_to_local_naive(self._date_mod)

    @property
    def start(self):
        return utc_to_local_naive(self._start)

    @property
    def get_short_meeting_topic(self):
        if len(str(self.topic)) > 24:
            return f"{self.topic[:20]} ..."
        else:
            return self.topic

    @property
    def is_today(self):
        if self.start.date() == datetime.today().date():
            return True
        print("not today:", self.start)
        return False

    @property
    def is_expired(self):
        if get_naive_dt(datetime.utcnow()).date() > get_naive_dt(self._start).date():
            return True


"""
=================================
    QUIZZES
=================================
"""


class Quiz(models.Model):
    classroom = models.ForeignKey(Classroom, on_delete=models.CASCADE)
    owner = models.ForeignKey(Lecturer, on_delete=models.CASCADE)
    title = models.CharField(max_length=300)
    description = models.TextField(null=True, blank=True)
    _date_created = models.DateTimeField(auto_now_add=True)
    _date_modified = models.DateTimeField(auto_now=True)
    _start = models.DateTimeField()
    duration = models.IntegerField()
    accept_after_expired = models.BooleanField(default=True)

    class Meta:
        unique_together = (('classroom', 'title'),)

    def __str__(self):
        return f"Quiz: {self.title}"

    @property
    def type(self):
        return 'quiz'

    @property
    def date_created(self):
        return utc_to_local_naive(self._date_created)

    @property
    def date_modified(self):
        return utc_to_local_naive(self._date_modified)

    @property
    def live(self):
        if self.start < datetime.now() < self.end:
            return True
        return False

    @property
    def expired(self):
        if datetime.now() > self.end:
            return True
        return False

    @property
    def start(self):
        return utc_to_local_naive(self._start)

    @property
    def end(self):
        return self.start + timedelta(minutes=float(self.duration))


class QuizQuestion(models.Model):
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)
    number = models.PositiveIntegerField()
    question = models.TextField(default="")

    def __str__(self):
        return f"Question: {self.question} -> [<Quiz: {self.quiz.title}>]"

    @property
    def correct_answers(self):
        return self.answer_set.filter(correct=True)

    @property
    def incorrect_answers(self):
        return self.answer_set.filter(correct=False)


LETTER_CHOICES = [
    ('A', 'A'),
    ('B', 'B'),
    ('C', 'C'),
    ('D', 'D'),
    ('E', 'E'),
    ('F', 'F'),
]


class QuizQuestionAnswer(models.Model):
    question = models.ForeignKey(QuizQuestion, on_delete=models.CASCADE)
    letter = models.CharField(max_length=1, choices=LETTER_CHOICES)
    answer = models.CharField(max_length=300, default="")
    correct = models.BooleanField(default=False)    # Whether answer is a correct or incorrect

    def __str__(self):
        return f"Answer: {self.answer} -> " \
               f"[<Quiz: {self.question.quiz.title}> -> " \
               f"<Question: {self.question.question}>]"

    @property
    def get_q_id(self):
        id_map = {'A': 1, 'B': 2, 'C': 3, 'D': 4, 'E': 5, 'F': 6}
        return id_map.get(str(self.letter))


class QuizStudentResponse(models.Model):
    """
    One single student response made by a student.
    """
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)
    owner = models.ForeignKey(Student, on_delete=models.CASCADE)
    _date_created = models.DateTimeField(auto_now_add=True)
    score = models.FloatField(default=0)

    def __str__(self):
        return f"Quiz Response by: {self.owner.user.get_full_name()}"

    @property
    def date_created(self):
        return utc_to_local_naive(self._date_created)


class QuizStudentResponseQuestion(models.Model):
    """
    <QuizStudentResponse> related.

    ONLY RELATED TO A ONE SINGLE <QuizStudentResponse> MADE BY A STUDENT.
    Do not use for anything else.
    """

classrooms/templates/classrooms/quizzes/parts/details-header.html
<!-- Top header content only for Quiz-details page -->

<div class="row post-author pb-4">
    <div class="col-8 text-left">
        <a href="{% url 'class-details' quiz.classroom.pk %}" class="text-left">
            <i class="fas fa-long-arrow-left pr-2"></i>Back to Classroom
        </a>
    </div><!-- col-8 -->
    <div class="col-4 text-right">
        {% if quiz.owner == user.profile %}
            <a href="{% url 'quiz-update' class_name=quiz.classroom.name|slugify pk=quiz.pk %}">
                <i class="fas fa-edit text-secondary"></i>
            </a>
            <a href="{% url 'quiz-delete' class_name=quiz.classroom.name|slugify pk=quiz.pk %}">
                <i class="fas fa-trash-alt ml-3 text-danger"></i>
            </a>
        {% endif %}
    </div><!-- col-4 -->
</div><!-- Edit and delete options for publisher -->

<!-- quiz details header -->
<div class="border-bottom">
    <h3 class="roboto-title-muted">{{ quiz.title }}</h3>
    <div class="row mb-2">
        <div class="col-12 mb-0">
            <span class="w-100 text-muted due-date"><small><b>Posted</b>: {{ quiz.date_created }},</small></span>
            <span class="w-100 text-muted due-date ml-2">
                <small><b>Last Updated:</b> {{ quiz.date_modified }}</small>
            </span>
        </div>
    </div>

    {% if user.is_lecturer %}
        <span class="mt-3 mb-3 d-block">
            <a href="{% url 'quiz-questions' class_name=quiz.classroom.name|slugify quiz_pk=quiz.pk %}"
               class="btn btn-info">
                Edit Questions
            </a>
        </span>
    {% endif %}
</div>

classrooms/templates/classrooms/quizzes/parts/details-lecturer.html
<!-- Quiz details page body for a lecturer -->

<div class="card-body">
    <table class="table table-borderless text-muted">
        <tr>
            <th>Scheduled at:</th>
            <td>{{ quiz.start }}</td>
        </tr>
        <tr>
            <th>Responses</th>
            <td>{{ quiz.quizstudentresponse_set.all.count }}</td>
        </tr>
    </table>

    <div class="row mt-4">
        <div class="col-12 text-center">
            {% if quiz.accepting_answers %}
                <a href="" class="btn btn-warning ml-auto">Stop Accepting Responses</a>
            {% endif %}
            <a href="{% url 'quiz-results' class_name=quiz.classroom.name|slugify quiz_pk=quiz.pk %}"
               class="btn btn-info">View Responses</a>
        </div>
    </div>
</div>

classrooms/templates/classrooms/quizzes/parts/details-student.html
<!-- Quiz details page body for a student -->

{% if quiz.description %}
    <div class="text-center p-4 card-header">
        {% if quiz.description %}
            <p class="mb-0">{{ quiz.description }}</p>
        {% endif %}
    </div>
{% endif %}

<div class="card-body">
    <div class="p-3 pt-0 text-center">
        {% if response %}
            <h4 class="roboto-title-muted mb-4">Score: {{ response.score }}%</h4>
            <a href="{% url 'quiz-response' class_name=quiz.classroom.name|slugify quiz_pk=quiz.pk %}"
               class="btn btn-success pl-4 pr-4 ml-auto ls-1">View Response</a>
            <h6 class="m-0 pt-4 roboto-title-muted">Responded on: {{ response.date_created }}</h6>
        {% else %}
            {% if quiz.expired and quiz.accept_after_expired %}
                <h5 class="pb-4 roboto-title text-danger">Missing</h5>
                <a href="{% url 'quiz-live' class_name=quiz.classroom.name|slugify quiz_pk=quiz.pk %}"
                   class="btn btn-success pl-4 pr-4 ml-auto">Start Quiz</a>
            {% elif quiz.expired and not quiz.accept_after_expired %}
                <h5 class="pb-4 roboto-title text-danger">Missing</h5>
                <h5 class="mb-0 roboto-title-muted mb-4">Started at: {{ quiz.start }}</h5>
            {% else %}
                <div class="row">
                    <div class="col-12">
                        <h5 class="mb-0 roboto-title-muted mb-4">Quiz starts in:</h5>
                        <h4 id="quizCountDown" class="roboto-title text-warning ml-2 mt-3 d-inline">
                            {{ time_counter }}
                        </h4>
                    </div>
                </div>
            {% endif %}
        {% endif %}<!-- not responded -->
    </div>
</div><!-- .card-body -->

classrooms/templates/classrooms/quizzes/parts/live.html
{% extends 'main/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="container pt-5 pb-5 min-body-height">
        <form method="POST" id="quizForm">
            {% csrf_token %}
            <div class="card shadow-sm p-4 mb-4"><!-- .questions area -->
                <div class="questions ml-2 mr-2 border-r-10" id="questionsArea">
                    <legend class="roboto-title-muted pb-2 text-center">{{ quiz.title }}</legend>
                    <p class="roboto-title-muted pb-2 text-center">{{ quiz.description }}</p>

                    <div class="quiz-info-row row border-bottom mb-5 mt-4 pb-2">
                        <div class="col-6">
                            <p class="m-0 roboto-title-muted">
                                <small>No of Questions: </small>
                                <a class="text-success" id="noOfQuestions">{{ quiz.quizquestion_set.all.count }}</a>
                            </p>
                        </div>
                        <div class="col-6">
                            <p class="roboto-title-muted m-0 text-right">
                                <small>Duration:</small> <a class="text-danger">{{ quiz.duration }} Minutes</a>
                            </p>
                        </div>
                    </div>

                    {% for q in quiz.quizquestion_set.all|dictsort:"number" %}
                        <div class='question p-2 mb-3'>
                            <table class='w-100'>
                                <tr>
                                    <td>
                                        <b class='roboto-title-muted' id='questionNumber'>{{ q.number }} )</b>
                                    </td>
                                    <td>
                                        <textarea rows=2
                                                  class="form-control"
                                                  disabled="true"
                                                  question-id="{{ q.number }}"
                                                  style="background-color: #fff;">{{ q.question }}</textarea>
                                    </td>
                                </tr>
                            </table>

                            <div class='row m-0 pt-3 answers-row w-100'>
                                <div class='col-12 p-0' id='answersRow'>
                                    <!-- All the answers goes here -->

                                    {% for answer in q.quizquestionanswer_set.all|dictsort:"letter" %}
                                        <div class='row w-100 m-0 mb-2 answer'>
                                            <div class='col-1 mt-auto mb-auto'></div>

                                            <div class="col-11 p-0">
                                                <table class='w-100'>
                                                    <tr>
                                                        <td class='mw-30' style="width: 25px;">
                                                            <p class='roboto-title-muted m-0' id='answerLetter'>
                                                                {{ answer.letter }}
                                                            </p>
                                                        </td>
                                                        <td id='answersCol'>
                                                            <input type='text'
                                                                   class='form-control answer-input'
                                                                   q-id="{{ answer.get_q_id }}"
                                                                   letter="{{ answer.letter }}"
                                                                   value="{{ answer.answer }}"
                                                                   correct="false"
                                                                   disabled="true"
                                                                   style="background-color: #fff;"
                                                            >
                                                        </td>
                                                        <td class="pl-3 mw-20">
                                                            <a class='text-danger answer-stat-toggle incorrect'
                                                               id='answerToggle'>
                                                                <i class='fas fa-check-circle fa-lg text-secondary'></i>
                                                            </a>
                                                        </td>
                                                    </tr>
                                                </table>
                                            </div>
                                        </div>
                                    {% endfor %}

                                </div>
                            </div>
                        </div>
                    {% endfor %}
                    <!-- All the questions will be appended here -->

                </div>
            </div><!-- .questions area -->

            <div class="row">
                <div class="col-12 text-center">
                    <a href="javascript:void(0);" class="btn btn-primary pl-4 pr-4 shadow-sm small-100" id="quizStudentResponseCreateBtn"
                       data-url="{% url 'quiz-live' class_name=quiz.classroom.name|slugify quiz_pk=quiz.pk %}">
                        Submit Response
                    </a>
                    <input type="hidden"
                           id="redirectFromQuizLive"
                           value="{% url 'quiz-response' class_name=quiz.classroom.name|slugify quiz_pk=quiz.pk %}">
                </div>
            </div>
        </form>
    </div>
{% endblock %}

classrooms/templates/classrooms/quizzes/parts/results.html
<!--   Only for a lecturer   -->
{% extends 'main/base.html' %}

{% block content %}
    <div class="container-fluid pt-3 min-body-height">
        <div class="container mt-3 mb-5">
            <legend class="roboto-title-muted border-bottom pb-2 mb-5 mt-4">Results for:
                <a href="{% url 'quiz-details' class_name=quiz.classroom.name|slugify pk=quiz.pk %}">
                    {{ quiz.title }}
                </a>
            </legend>

            {% for result in responses %}
                <table class="w-100 p-3 bg-white shadow-sm text-muted table rounded">
                    <tr>
                        <td class="col-5 m-auto border-0">
                            <h6 class="m-0 roboto-title-muted">{{ result.owner.user.get_full_name }}</h6>
                        </td>
                        <td class="col-4 m-auto border-0">
                            <h6 class="m-0">{{ result.owner.reg_no }}</h6>
                        </td>
                        <td class="col-3 m-auto border-0 text-center">
                            <h6 class="m-0">{{ result.score }}%</h6>
                        </td>
                    </tr>
                </table>
            {% empty %}
                <h3 class="roboto-title-muted w-100 text-center" style="margin-top: 150px;">
                    No Responses
                </h3>
            {% endfor %}

        </div><!-- .container -->
    </div><!-- .container-fluid -->
{% endblock %}