classrooms/urls.py
from django.urls import path
from . import views
from . import fetchviews


urlpatterns = [
    path('classrooms/',
         views.ClassroomListView.as_view(), name='classrooms'),
    path('classroom/create-new/',
         views.ClassroomCreateView.as_view(), name='class-create'),
    path('classroom/<str:pk>/',
         views.ClassroomDetailView.as_view(), name='class-details'),
    path('classroom/<str:pk>/edit/',
         views.ClassroomUpdateView.as_view(), name='class-update'),
    path('classroom/<str:pk>/delete/',
         views.ClassroomDeleteView.as_view(), name='class-delete'),
    path('classroom/<str:pk>/post/create-new/',
         views.PostCreateView.as_view(), name='post-new'),
    path('classroom/<str:class_pk>/post/<str:pk>/',
         views.PostDetailView.as_view(), name='post-details'),
    path('classroom/<str:class_pk>/post/<str:pk>/update/',
         views.PostUpdateView.as_view(), name='post-update'),
    path('classroom/<str:class_pk>/post/<str:pk>/delete/',
         views.PostDeleteView.as_view(), name='post-delete'),
    path('classroom/<str:class_pk>/assignment/create-new/',
         views.AssignmentCreateView.as_view(), name='assignment-new'),
    path('classroom/<str:class_name>/assignment/<str:pk>/',
         views.assignment_detail_view, name='assignment-details'),
    path('classroom/<str:class_name>/assignment/<str:pk>/update/',
         views.AssignmentUpdateView.as_view(), name='assignment-update'),
    path('classroom/<str:class_name>/assignment/<str:pk>/delete/',
         views.AssignmentDeleteView.as_view(), name='assignment-delete'),
    path('classroom/<str:class_name>/assignment/<str:pk>/unsubmit/'
         '', views.assignment_unsubmit_view, name='assignment-unsubmit'),
    path('classroom/<str:class_name>/assignment/<str:assignment_pk>/submission-details/',
         views.assignment_submissions_view, name='submit-details'),
    path('complete-review/<str:assignment_pk>/',
         views.assignment_complete_review_view, name='complete-review'),
    path('undo-complete-review/<str:assignment_pk>/',
         views.assignment_undo_complete_review_view, name='undo-review-complete'),
    path('assignments/all/<str:type>/',
         views.AssignmentListView.as_view(), name='assignments-list'),

    # Quizzes Urls
    path('quizzes/<str:type>/',
         views.QuizListView.as_view(), name='quiz-list'),
    path('classroom/<str:pk>/quiz/create-new/',
         views.QuizCreateView.as_view(), name='quiz-create'),
    path('classroom/<str:class_name>/quiz/<str:pk>/details/',
         views.QuizDetailView.as_view(), name='quiz-details'),
    path('classroom/<str:class_name>/quiz/<str:pk>/delete/',
         views.QuizDeleteView.as_view(), name='quiz-delete'),
    path('classroom/<str:class_name>/quiz/<str:pk>/edit/',
         views.QuizUpdateView.as_view(), name='quiz-update'),

    # Quiz question url
    path('classroom/<str:class_name>/quiz/<str:quiz_pk>/questions/',
         views.quiz_questions_and_answers_view, name='quiz-questions'),
    path('classroom/<str:class_name>/quiz/<str:quiz_pk>/live',
         views.quiz_live_view, name='quiz-live'),

    # Quiz response details page made by a student
    path('classroom/<str:class_name>/quiz/<str:quiz_pk>/response',
         views.quiz_stu_response_view, name='quiz-response'),

    # Quiz results page (for lecturer)
    path('classroom/<str:class_name>/quiz/<str:quiz_pk>/results',
         views.QuizResultsView.as_view(), name='quiz-results'),

    # Other fetch views
    path('classroom/<str:class_name>/quiz/<str:quiz_pk>/countdown',
         fetchviews.quiz_start_time_view, name='quiz-countdown'),


    # Meeting Urls
    path('meetings/<str:type>/',
         views.MeetingListView.as_view(), name='meetings-list'),
    path('classroom/<str:pk>/meeting/create-new/',
         views.MeetingCreateView.as_view(), name='meeting-create'),
    path('classroom/<str:class_name>/meeting/<str:pk>/details/',
         views.MeetingDetailView.as_view(), name='meeting-details'),
    path('classroom/<str:class_name>/meeting/<str:pk>/delete/',
         views.MeetingDeleteView.as_view(), name='meeting-delete'),
    path('classroom/<str:class_name>/meeting/<str:pk>/edit/',
         views.MeetingUpdateView.as_view(), name='meeting-update'),
]

django_LMS/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('', include('users.urls')),
    path('', include('classrooms.urls')),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

main/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name="home"),
    path('events-today/', views.today_events, name='events-today'),

]

classrooms/models.py
import os.path
from datetime import datetime, timedelta
from django.db import models
from users.models import CustomizedUser, Student, Lecturer
from main.models import Batch, Department
from ckeditor.fields import RichTextField
from main.funcs import (
    local_to_utc_aware,
    local_to_utc_naive,
    utc_to_local_aware,
    utc_to_local_naive,
    get_naive_dt
)


class Classroom(models.Model):
    owner = models.ForeignKey(Lecturer, on_delete=models.CASCADE, related_name='owner')
    department = models.ForeignKey(Department, on_delete=models.CASCADE)
    lecturers = models.ManyToManyField(Lecturer)
    name = models.CharField(max_length=300)
    description = models.TextField(max_length=150, null=True,  blank=True)
    background_img = models.ImageField(null=True, blank=True)
    date_created = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = (('department', 'name'),)

    def __str__(self):
        return f"Class: {self.name} [{self.department}]"


class Post(models.Model):
    classroom = models.ForeignKey(Classroom, on_delete=models.CASCADE)
    owner = models.ForeignKey(Lecturer, on_delete=models.CASCADE)
    title = models.CharField(max_length=300)
    _date_created = models.DateTimeField(auto_now_add=True)
    date_last_mod = models.DateTimeField(auto_now=True)
    content = RichTextField(blank=True, null=True)

    class Meta:
        unique_together = (('classroom', 'title'),)

    @property
    def date_created(self):
        return get_naive_dt(self._date_created)

    def __str__(self):
        return f"Post: {self.title} [{self.classroom}]"


"""
=================================
    ASSIGNMENT
=================================
"""


class Assignment(models.Model):
    classroom = models.ForeignKey(Classroom, on_delete=models.CASCADE)
    owner = models.ForeignKey(Lecturer, on_delete=models.CASCADE)
    type = models.CharField(max_length=8, default='regular',
                            choices=[('regular', 'Regular'),
                                     ('question', 'Question')])
    title = models.CharField(max_length=300)
    _date_created = models.DateTimeField(auto_now_add=True)
    _date_last_mod = models.DateTimeField(auto_now=True)
    _date_due = models.DateTimeField()
    content = RichTextField()   # From CK Editor
    file = models.FileField(null=True, blank=True, upload_to='assignment-files')  # This won't be used actually
    review_complete = models.BooleanField(default=False)

    class Meta:
        unique_together = (('title', 'classroom'),)

    def __str__(self):
        return f"Assignment: {self.title} [ {self.classroom} ]"

    @property
    def type(self):
        return "assignment"

    @property
    def date_created(self):
        return utc_to_local_naive(self._date_created)

    @property
    def date_due(self):
        return utc_to_local_naive(self._date_due)

    @property
    def date_mod(self):
        return utc_to_local_naive(self._date_last_mod)

    @property
    def expired(self):
        if get_naive_dt(self.date_due) < get_naive_dt(datetime.utcnow()):
            return True
        return False

    @property
    def pending_submissions(self) -> int:
        _all_stu = self.classroom.department.student_set.count()
        _all_sub_done = self.submission_set.count()
        pending = int(_all_stu) - int(_all_sub_done)
        return pending


class Submission(models.Model):
    assignment = models.ForeignKey(Assignment, on_delete=models.CASCADE)
    owner = models.ForeignKey(Student, on_delete=models.CASCADE)
    _date_created = models.DateTimeField(auto_now_add=True)
    grade = models.CharField(max_length=20, null=True, blank=True)
    file = models.FileField(blank=True, null=True)  # this should not be saved. instead, <SubmissionFile> will be used.
    lec_comment = models.TextField(null=True, blank=True)

    def __str__(self):
        return f"Submission By: {self.owner.user.username}" \
               f" [Assignment-> {self.assignment.title}]"

    @property
    def date_created(self):
        return utc_to_local_naive(self._date_created)

    @property
    def is_late_submit(self):
        """
        If the submission is a late submit or not.
        :return:
        """
        if self.date_created > self.assignment.date_due:
            return True
        return False


class SubmissionFile(models.Model):
    """
    Used for multiple file upload functionality
    """
    submission = models.ForeignKey(Submission, on_delete=models.CASCADE)
    file = models.FileField(upload_to='submission-files')

    def get_short_file_name(self):
        name = self.file.name
        return os.path.basename(name)[-28:]


"""
=================================
    MEETING
=================================
"""


class Meeting(models.Model):
    classroom = models.ForeignKey(Classroom, on_delete=models.CASCADE)
    owner = models.ForeignKey(Lecturer, on_delete=models.CASCADE)
    topic = models.CharField(max_length=300)
    _date_created = models.DateTimeField(auto_now_add=True)
    _date_mod = models.DateTimeField(auto_now=True)
    _start = models.DateTimeField()
    description = models.TextField(null=True, blank=True)
    meeting_url = models.URLField(null=True, blank=True)
    meeting_id = models.CharField(null=True, blank=True, max_length=300)
    meeting_pwd = models.CharField(null=True, blank=True, max_length=200)
    recording_url = models.URLField(null=True, blank=True)

    class Meta:
        unique_together = (('classroom', 'topic'),)

    def __str__(self):
        return f"Meeting: {self.topic} [Class-> {self.classroom.name}" \
               f" {self.classroom.department.batch.year} Batch]"

    @property
    def type(self):
        return 'meeting'

    @property
    def date_created(self):
        return utc_to_local_naive(self._date_created)

    @property
    def date_mod(self):
        return utc_to_local_naive(self._date_mod)

    @property
    def start(self):
        return utc_to_local_naive(self._start)

    @property
    def get_short_meeting_topic(self):
        if len(str(self.topic)) > 24:
            return f"{self.topic[:20]} ..."
        else:
            return self.topic

    @property
    def is_today(self):
        if self.start.date() == datetime.today().date():
            return True
        print("not today:", self.start)
        return False

    @property
    def is_expired(self):
        if get_naive_dt(datetime.utcnow()).date() > get_naive_dt(self._start).date():
            return True


"""
=================================
    QUIZZES
=================================
"""


class Quiz(models.Model):
    classroom = models.ForeignKey(Classroom, on_delete=models.CASCADE)
    owner = models.ForeignKey(Lecturer, on_delete=models.CASCADE)
    title = models.CharField(max_length=300)
    description = models.TextField(null=True, blank=True)
    _date_created = models.DateTimeField(auto_now_add=True)
    _date_modified = models.DateTimeField(auto_now=True)
    _start = models.DateTimeField()
    duration = models.IntegerField()
    accept_after_expired = models.BooleanField(default=True)

    class Meta:
        unique_together = (('classroom', 'title'),)

    def __str__(self):
        return f"Quiz: {self.title}"

    @property
    def type(self):
        return 'quiz'

    @property
    def date_created(self):
        return utc_to_local_naive(self._date_created)

    @property
    def date_modified(self):
        return utc_to_local_naive(self._date_modified)

    @property
    def live(self):
        if self.start < datetime.now() < self.end:
            return True
        return False

    @property
    def expired(self):
        if datetime.now() > self.end:
            return True
        return False

    @property
    def start(self):
        return utc_to_local_naive(self._start)

    @property
    def end(self):
        return self.start + timedelta(minutes=float(self.duration))


class QuizQuestion(models.Model):
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)
    number = models.PositiveIntegerField()
    question = models.TextField(default="")

    def __str__(self):
        return f"Question: {self.question} -> [<Quiz: {self.quiz.title}>]"

    @property
    def correct_answers(self):
        return self.answer_set.filter(correct=True)

    @property
    def incorrect_answers(self):
        return self.answer_set.filter(correct=False)


LETTER_CHOICES = [
    ('A', 'A'),
    ('B', 'B'),
    ('C', 'C'),
    ('D', 'D'),
    ('E', 'E'),
    ('F', 'F'),
]


class QuizQuestionAnswer(models.Model):
    question = models.ForeignKey(QuizQuestion, on_delete=models.CASCADE)
    letter = models.CharField(max_length=1, choices=LETTER_CHOICES)
    answer = models.CharField(max_length=300, default="")
    correct = models.BooleanField(default=False)    # Whether answer is a correct or incorrect

    def __str__(self):
        return f"Answer: {self.answer} -> " \
               f"[<Quiz: {self.question.quiz.title}> -> " \
               f"<Question: {self.question.question}>]"

    @property
    def get_q_id(self):
        id_map = {'A': 1, 'B': 2, 'C': 3, 'D': 4, 'E': 5, 'F': 6}
        return id_map.get(str(self.letter))


class QuizStudentResponse(models.Model):
    """
    One single student response made by a student.
    """
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)
    owner = models.ForeignKey(Student, on_delete=models.CASCADE)
    _date_created = models.DateTimeField(auto_now_add=True)
    score = models.FloatField(default=0)

    def __str__(self):
        return f"Quiz Response by: {self.owner.user.get_full_name()}"

    @property
    def date_created(self):
        return utc_to_local_naive(self._date_created)


class QuizStudentResponseQuestion(models.Model):
    """
    <QuizStudentResponse> related.

    ONLY RELATED TO A ONE SINGLE <QuizStudentResponse> MADE BY A STUDENT.
    Do not use for anything else.
    """

classrooms/templates/template-parts/assign-details-sidebar-lec-card.html
<!-- Sidebar card for a lecturer in assignment details page -->

<div class="card assignment-sidebar-card shadow mw-400 m-auto">
    <div class="card-header">
        <div class="row">
            <div class="col-12 text-muted">
                <h6 class="font-weight-bold pt-2">Assignment Status</h6>
            </div>
        </div>
    </div><!-- .card-header -->

    <div class="card-body text-left text-muted">
        <table class="table table-striped">
            <tbody class="text-left text-secondary">
                <tr>
                    <th scope="row"><span>Total Submissions:</span></th>
                    <td><b>{{ assignment.submission_set.count }}</b></td>
                </tr>
                <tr>
                    <th scope="row"><span>Pending:</span></th>
                    <td>{{ assignment.pending_submissions }}</td>
                </tr>
            </tbody>
        </table>

        <a class="pt-3 pb-3 text-center d-block">
            {% if assignment.review_complete %}
                Review Completed<i class="fas fa-check-circle ml-2 text-success"></i>
            {% else %}
                Pending Review<i class="fas fa-info-circle ml-2"></i>
            {% endif %}
        </a>

        <a href="{% url 'submit-details' class_name=assignment.classroom.name|slugify assignment_pk=assignment.pk %}"
           class="btn btn-info w-100">
            View Submissions
        </a>
    </div>
</div>

classrooms/templates/template-parts/assign-details-sidebar-stu-card.html
<div class="card assignment-sidebar-card shadow mw-400 m-auto">
    <div class="card-header">
        <div class="row">
            <div class="col-6 text-left">
                <h5 class="pt-2">Your Work</h5>
            </div>
            <div class="col-6 text-right">
                <h6 class="pt-2 text-muted">
                    {% if submission %}
                        {% if submission.is_late_submit %}
                            <b class="text-danger">Late Submission</b>
                        {% else %}
                             <b class="text-success">Turned In</b>
                        {% endif %}
                    {% else %}
                        {% if assignment.expired %}
                             <b class="text-danger">Missing</b>
                        {% else %}
                             <b class="text-secondary">Pending</b>
                        {% endif %}
                    {% endif %}
                </h6>
            </div>
        </div>
    </div><!-- .card-header -->

    <div class="card-body">
        <div class="row">
            <div class="col-12">
                <div class="selected-files pt-3 pb-4" id="selectedFiles">
                    {% if submission %}
                        {% for f in submission.submissionfile_set.all %}
                            <a class="border p-2 w-100 d-block rounded mb-2 shadow-sm"
                                href="{{ f.file.url }}" target="_blank">
                                {{ f.get_short_file_name }}
                            </a>
                        {% empty %}
                            <p class="m-0">No Files Submitted</p>
                        {% endfor %}
                    {% endif %}
                </div>

                {% if not submission %}
                    {% if not assignment.review_complete %}
                        <form method="POST" enctype="multipart/form-data" class="assignment-file-input">
                            <div class="custom-file mb-2">
                                {% csrf_token %}
                                {{ form }}
                            </div>
                            <small>maximum of 3 files allowed</small>
                            <button class="btn btn-success w-100 mt-4">Submit</button>
                        </form>
                    {% else %}
                        <a class="btn btn-info disabled text-light w-100">Submissions Not Accepting</a>
                    {% endif %}
                {% else %}

                    <!--
                    UnSubmission should only be allowed if the lecturer has not finished the assignment
                    review and also if not the assignment is graded
                    -->
                    {% if submission.grade %}
                        <a href="" class="btn btn-info w-100 disabled">Graded</a>
                    {% elif assignment.review_complete  %}
                        <a href="" class="btn btn-info w-100 disabled">Review Completed</a>
                    {% else %}
                        <a href="#" class="btn btn-danger w-100 mt-3"
                           data-toggle="modal" data-target="#unsubmitModelConfirm">UnSubmit
                        </a>
                    {% endif %}

                    <!-- Popup that opens when enrolling -->
                    <div class="modal fade" id="unsubmitModelConfirm" tabindex="-1" role="dialog"
                         aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
                        <div class="modal-dialog modal-dialog-centered" role="document">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="exampleModalLongTitle">Are you sure ?</h5>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                <div class="modal-body text-left">
                                    This action cannot be undone. Your previous submission
                                    will be completely removed.
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                    <a href="{% url 'assignment-unsubmit' class_name=assignment.classroom.name|slugify pk=assignment.pk %}"
                                       class="btn btn-danger">Unsubmit</a>
                                </div>
                            </div>
                        </div>
                    </div><!-- .model popup unsubmit-confirm -->
                {% endif %}
            </div><!-- .col-12 -->
        </div><!-- .row -->
    </div><!-- .card-body -->

    <div class="card-footer">
        <h6 class="text-center roboto-title-muted">Results</h6>
        <table class="table table-striped mt-4">
            <tbody class="text-left text-secondary">
                <tr>
                    <th scope="row"><span>Grade</span></th>
                    <td><b>
                        {% if submission.grade %}
                            {{ submission.grade }}
                        {% else %}
                            Not Graded
                        {% endif %}
                    </b></td>
                </tr>
                <tr>
                    <th scope="row"><span>Lecturer Comment</span></th>
                    <td>{{ submission.lec_comment }}</td>
                </tr>
            </tbody>
        </table>
    </div><!-- .card-footer -->
</div>

classrooms/templates/template-parts/class-assignment-item.html
<div class="card post-card mb-3 pl-2 pr-3 pt-2 pb-2 border-r-10">
    <table class="">
        <tr>
            <td class="pr-3 text-muted" style="width: 50px;">
                <i class="fa-brands fa-leanpub p-3" style="color: #999999;"></i>
            </td>
            <td>
                <a href="{% url 'assignment-details' class_name=work.classroom.name|slugify pk=work.pk %}"
                   class="m-0 text-info roboto-title-muted">
                    <span style="color: #737373;">Assignment:</span> {{ work.title }}
                </a><br/>
                <small class="m-0 pr-2">{{ work.date_created }}</small>
                <small>By: {{ work.owner.user.get_full_name }}</small>
            </td>
        </tr>
    </table>
</div>

classrooms/templates/template-parts/class-meeting-item.html
<div class="card post-card mb-3 pl-2 pr-3 pt-2 pb-2 border-r-10">
    <table class="">
        <tr>
            <td class="pr-3 text-muted" style="width: 50px;">
                <i class="fas fa-video p-3" style="color: #999999;"></i>
            </td>
            <td>
                <a href="{% url 'meeting-details' class_name=work.classroom.name|slugify pk=work.pk %}"
                   class="m-0 text-info roboto-title-muted">
                    <span style="color: #737373;">Meeting:</span> {{ work.topic }}
                </a><br/>
                <small class="m-0 pr-2">{{ work.date_created }}</small>
                <small>By: {{ work.owner.user.get_full_name }}</small>
            </td>
        </tr>
    </table>
</div>

classrooms/templates/template-parts/class-post-item.html
<div class="card post-card mb-3 pl-2 pr-3 pt-2 pb-2 border-r-10">
    <table class="">
        <tr>
            <td class="pr-3 text-muted" style="width: 50px;">
                <i class="fa-solid fa-pencil p-3"
                   style="color: #999999;">
                </i>
            </td>
            <td>
                <a href="{% url 'post-details' class_pk=class.pk pk=post.pk %}"
                   class="m-0 text-info roboto-title-muted">{{ post.title }}
                </a><br/>
                <small class="m-0">{{ post.date_created }}</small>
            </td>
        </tr>
    </table>
</div>

classrooms/templates/template-parts/class-quiz-item.html
<div class="card post-card mb-3 pl-2 pr-3 pt-2 pb-2 border-r-10">
    <table class="">
        <tr>
            <td class="pr-3 text-muted" style="width: 50px;">
                <i class="fas fa-feather p-3" style="color: #999999;"></i>
            </td>
            <td>
                <a href="{% url 'quiz-details' class_name=work.classroom.name|slugify pk=work.pk %}"
                   class="m-0 text-info roboto-title-muted">
                    <span style="color: #737373;">Quiz:</span> {{ work.title }}
                </a><br/>
                <small class="m-0 pr-2">{{ work.date_created }}</small>
                <small>By: {{ work.owner.user.get_full_name }}</small>
            </td>
        </tr>
    </table>
</div>

classrooms/templates/template-parts/file.html
{% comment %}
    ->  This template part is used to render file objects anywhere in the app

    args:
        -> file: Any file object
        -> ext: File Extension
        -> design: [box, rectangle]
        -> download: bool
{% endcomment %}

<div class="card shadow-sm border-r-10 text-center m-3" style="width: 110px">
    <a href="{{ file.url }}" target="_blank" style="padding-top: 15px;">
        <i class="fas fa-file-alt" style="font-size: 30px;"></i>
    </a>
    <div style="padding-bottom: 10px; padding-top: 10px;">
        <a href="{{ file.url }}" {{ download }} class="text-primary">
            Download
        </a>
    </div>
</div>

classrooms/templates/template-parts/submission-detail-item.html
{% load crispy_forms_tags %}

{% comment %}
    This template part is used in following pages
        -> submission-details.html
{% endcomment %}

<div class="card mb-2 submit-detail-item">
    <div class="card-header" id="headingOne">
        <h5 class="mb-0">
            <div class="row">
                <div class="col-7">
                    <img src="{{ profile.profile_pic.url }}" class="btn-link rounded-circle"
                         style="max-width: 40px; max-height: 40px">
                    <a class="btn btn-link">{{ profile.user.get_full_name }}</a>
                </div>
                <div class="col-3">
                    <a class="btn btn-link">
                        {% if submission %}
                            {% if submission.grade %}
                                <b class="text-success">Graded</b>
                            {% else %}
                                <b class="text-warning">Pending Review</b>
                            {% endif %}
                        {% else %}
                            Not Submitted
                        {% endif %}
                    </a>
                </div>
                <div class="col-2 text-right">
                    {% if submission %}
                        <a class="btn btn-link show-submission" data-toggle="collapse"
                           data-target="#collapse{{ submission.pk }}"
                           aria-expanded="true" aria-controls="collapseOne">
                            <i class="fas fa-chevron-circle-down"></i>
                        </a>
                    {% endif %}
                </div>
            </div>
        </h5>
    </div>
    {% if submission %}
        <div id="collapse{{ submission.pk }}" class="collapse p-0" aria-labelledby="headingOne" data-parent="#accordion">
            <div class="row w-100 m-0">
                <div class="col-sm-12 col-lg-4 p-0 mb-3 border-right">
                    <div class="type pl-3 text-center">
                        <h6 class="pb-2 pt-2 roboto-title">Files</h6>
                    </div>
                    <div class="p-3">
                        {% for sub in submission.submissionfile_set.all %}
                            {% include "template-parts/file.html" with file=sub.file design="box" download='download' %}
                        {% empty %}
                            <h6 class="mt-5">No Files Submitted</h6>
                        {% endfor %}
                    </div>
                </div><!-- .col-lg-4 -->
                <div class="col-sm-12 col-lg-4 p-0 mb-3 border-right">
                    <div class="type pl-3 text-center">
                        <h6 class="pb-2 pt-2 roboto-title">Submission Details</h6>
                    </div>
                    <div class="p-3">
                        <table class="table table-striped">
                            <tbody>
                                <tr>
                                    <th scope="row">Date:</th>
                                    <td>{{ submission.date_created }}</td>
                                </tr>
                                <tr>
                                    <th scope="row">Reg No:</th>
                                    <td>{{ submission.owner.reg_no }}</td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div><!-- .col-lg-4 -->
                <div class="col-sm-12 col-lg-4 p-0 mb-3 border-right">
                    <div class="type pl-3 text-center">
                        <h6 class="pb-2 pt-2 roboto-title">Evaluation</h6>
                    </div>
                    <div class="p-3">
                        <form method="POST">
                            {% csrf_token %}
                            {{ submission.form|crispy }}
                            <input type="hidden" name="u_profile_id" value="{{ submission.owner.pk }}">
                            <button type="submit" class="btn btn-info">Evaluate</button>
                        </form>
                    </div>
                </div><!-- .col-lg-4 -->
            </div><!-- .row -->
        </div><!-- .collapse -->
    {% endif %}
</div>