classrooms/urls.py
from django.urls import path
from . import views
from . import fetchviews


urlpatterns = [
    path('classrooms/',
         views.ClassroomListView.as_view(), name='classrooms'),
    path('classroom/create-new/',
         views.ClassroomCreateView.as_view(), name='class-create'),
    path('classroom/<str:pk>/',
         views.ClassroomDetailView.as_view(), name='class-details'),
    path('classroom/<str:pk>/edit/',
         views.ClassroomUpdateView.as_view(), name='class-update'),
    path('classroom/<str:pk>/delete/',
         views.ClassroomDeleteView.as_view(), name='class-delete'),
    path('classroom/<str:pk>/post/create-new/',
         views.PostCreateView.as_view(), name='post-new'),
    path('classroom/<str:class_pk>/post/<str:pk>/',
         views.PostDetailView.as_view(), name='post-details'),
    path('classroom/<str:class_pk>/post/<str:pk>/update/',
         views.PostUpdateView.as_view(), name='post-update'),
    path('classroom/<str:class_pk>/post/<str:pk>/delete/',
         views.PostDeleteView.as_view(), name='post-delete'),
    path('classroom/<str:class_pk>/assignment/create-new/',
         views.AssignmentCreateView.as_view(), name='assignment-new'),
    path('classroom/<str:class_name>/assignment/<str:pk>/',
         views.assignment_detail_view, name='assignment-details'),
    path('classroom/<str:class_name>/assignment/<str:pk>/update/',
         views.AssignmentUpdateView.as_view(), name='assignment-update'),
    path('classroom/<str:class_name>/assignment/<str:pk>/delete/',
         views.AssignmentDeleteView.as_view(), name='assignment-delete'),
    path('classroom/<str:class_name>/assignment/<str:pk>/unsubmit/'
         '', views.assignment_unsubmit_view, name='assignment-unsubmit'),
    path('classroom/<str:class_name>/assignment/<str:assignment_pk>/submission-details/',
         views.assignment_submissions_view, name='submit-details'),
    path('complete-review/<str:assignment_pk>/',
         views.assignment_complete_review_view, name='complete-review'),
    path('undo-complete-review/<str:assignment_pk>/',
         views.assignment_undo_complete_review_view, name='undo-review-complete'),
    path('assignments/all/<str:type>/',
         views.AssignmentListView.as_view(), name='assignments-list'),

    # Quizzes Urls
    path('quizzes/<str:type>/',
         views.QuizListView.as_view(), name='quiz-list'),
    path('classroom/<str:pk>/quiz/create-new/',
         views.QuizCreateView.as_view(), name='quiz-create'),
    path('classroom/<str:class_name>/quiz/<str:pk>/details/',
         views.QuizDetailView.as_view(), name='quiz-details'),
    path('classroom/<str:class_name>/quiz/<str:pk>/delete/',
         views.QuizDeleteView.as_view(), name='quiz-delete'),
    path('classroom/<str:class_name>/quiz/<str:pk>/edit/',
         views.QuizUpdateView.as_view(), name='quiz-update'),

    # Quiz question url
    path('classroom/<str:class_name>/quiz/<str:quiz_pk>/questions/',
         views.quiz_questions_and_answers_view, name='quiz-questions'),
    path('classroom/<str:class_name>/quiz/<str:quiz_pk>/live',
         views.quiz_live_view, name='quiz-live'),

    # Quiz response details page made by a student
    path('classroom/<str:class_name>/quiz/<str:quiz_pk>/response',
         views.quiz_stu_response_view, name='quiz-response'),

    # Quiz results page (for lecturer)
    path('classroom/<str:class_name>/quiz/<str:quiz_pk>/results',
         views.QuizResultsView.as_view(), name='quiz-results'),

    # Other fetch views
    path('classroom/<str:class_name>/quiz/<str:quiz_pk>/countdown',
         fetchviews.quiz_start_time_view, name='quiz-countdown'),


    # Meeting Urls
    path('meetings/<str:type>/',
         views.MeetingListView.as_view(), name='meetings-list'),
    path('classroom/<str:pk>/meeting/create-new/',
         views.MeetingCreateView.as_view(), name='meeting-create'),
    path('classroom/<str:class_name>/meeting/<str:pk>/details/',
         views.MeetingDetailView.as_view(), name='meeting-details'),
    path('classroom/<str:class_name>/meeting/<str:pk>/delete/',
         views.MeetingDeleteView.as_view(), name='meeting-delete'),
    path('classroom/<str:class_name>/meeting/<str:pk>/edit/',
         views.MeetingUpdateView.as_view(), name='meeting-update'),
]

django_LMS/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('', include('users.urls')),
    path('', include('classrooms.urls')),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

main/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name="home"),
    path('events-today/', views.today_events, name='events-today'),

]

classrooms/models.py
import os.path
from datetime import datetime, timedelta
from django.db import models
from users.models import CustomizedUser, Student, Lecturer
from main.models import Batch, Department
from ckeditor.fields import RichTextField
from main.funcs import (
    local_to_utc_aware,
    local_to_utc_naive,
    utc_to_local_aware,
    utc_to_local_naive,
    get_naive_dt
)


class Classroom(models.Model):
    owner = models.ForeignKey(Lecturer, on_delete=models.CASCADE, related_name='owner')
    department = models.ForeignKey(Department, on_delete=models.CASCADE)
    lecturers = models.ManyToManyField(Lecturer)
    name = models.CharField(max_length=300)
    description = models.TextField(max_length=150, null=True,  blank=True)
    background_img = models.ImageField(null=True, blank=True)
    date_created = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = (('department', 'name'),)

    def __str__(self):
        return f"Class: {self.name} [{self.department}]"


class Post(models.Model):
    classroom = models.ForeignKey(Classroom, on_delete=models.CASCADE)
    owner = models.ForeignKey(Lecturer, on_delete=models.CASCADE)
    title = models.CharField(max_length=300)
    _date_created = models.DateTimeField(auto_now_add=True)
    date_last_mod = models.DateTimeField(auto_now=True)
    content = RichTextField(blank=True, null=True)

    class Meta:
        unique_together = (('classroom', 'title'),)

    @property
    def date_created(self):
        return get_naive_dt(self._date_created)

    def __str__(self):
        return f"Post: {self.title} [{self.classroom}]"


"""
=================================
    ASSIGNMENT
=================================
"""


class Assignment(models.Model):
    classroom = models.ForeignKey(Classroom, on_delete=models.CASCADE)
    owner = models.ForeignKey(Lecturer, on_delete=models.CASCADE)
    type = models.CharField(max_length=8, default='regular',
                            choices=[('regular', 'Regular'),
                                     ('question', 'Question')])
    title = models.CharField(max_length=300)
    _date_created = models.DateTimeField(auto_now_add=True)
    _date_last_mod = models.DateTimeField(auto_now=True)
    _date_due = models.DateTimeField()
    content = RichTextField()   # From CK Editor
    file = models.FileField(null=True, blank=True, upload_to='assignment-files')  # This won't be used actually
    review_complete = models.BooleanField(default=False)

    class Meta:
        unique_together = (('title', 'classroom'),)

    def __str__(self):
        return f"Assignment: {self.title} [ {self.classroom} ]"

    @property
    def type(self):
        return "assignment"

    @property
    def date_created(self):
        return utc_to_local_naive(self._date_created)

    @property
    def date_due(self):
        return utc_to_local_naive(self._date_due)

    @property
    def date_mod(self):
        return utc_to_local_naive(self._date_last_mod)

    @property
    def expired(self):
        if get_naive_dt(self.date_due) < get_naive_dt(datetime.utcnow()):
            return True
        return False

    @property
    def pending_submissions(self) -> int:
        _all_stu = self.classroom.department.student_set.count()
        _all_sub_done = self.submission_set.count()
        pending = int(_all_stu) - int(_all_sub_done)
        return pending


class Submission(models.Model):
    assignment = models.ForeignKey(Assignment, on_delete=models.CASCADE)
    owner = models.ForeignKey(Student, on_delete=models.CASCADE)
    _date_created = models.DateTimeField(auto_now_add=True)
    grade = models.CharField(max_length=20, null=True, blank=True)
    file = models.FileField(blank=True, null=True)  # this should not be saved. instead, <SubmissionFile> will be used.
    lec_comment = models.TextField(null=True, blank=True)

    def __str__(self):
        return f"Submission By: {self.owner.user.username}" \
               f" [Assignment-> {self.assignment.title}]"

    @property
    def date_created(self):
        return utc_to_local_naive(self._date_created)

    @property
    def is_late_submit(self):
        """
        If the submission is a late submit or not.
        :return:
        """
        if self.date_created > self.assignment.date_due:
            return True
        return False


class SubmissionFile(models.Model):
    """
    Used for multiple file upload functionality
    """
    submission = models.ForeignKey(Submission, on_delete=models.CASCADE)
    file = models.FileField(upload_to='submission-files')

    def get_short_file_name(self):
        name = self.file.name
        return os.path.basename(name)[-28:]


"""
=================================
    MEETING
=================================
"""


class Meeting(models.Model):
    classroom = models.ForeignKey(Classroom, on_delete=models.CASCADE)
    owner = models.ForeignKey(Lecturer, on_delete=models.CASCADE)
    topic = models.CharField(max_length=300)
    _date_created = models.DateTimeField(auto_now_add=True)
    _date_mod = models.DateTimeField(auto_now=True)
    _start = models.DateTimeField()
    description = models.TextField(null=True, blank=True)
    meeting_url = models.URLField(null=True, blank=True)
    meeting_id = models.CharField(null=True, blank=True, max_length=300)
    meeting_pwd = models.CharField(null=True, blank=True, max_length=200)
    recording_url = models.URLField(null=True, blank=True)

    class Meta:
        unique_together = (('classroom', 'topic'),)

    def __str__(self):
        return f"Meeting: {self.topic} [Class-> {self.classroom.name}" \
               f" {self.classroom.department.batch.year} Batch]"

    @property
    def type(self):
        return 'meeting'

    @property
    def date_created(self):
        return utc_to_local_naive(self._date_created)

    @property
    def date_mod(self):
        return utc_to_local_naive(self._date_mod)

    @property
    def start(self):
        return utc_to_local_naive(self._start)

    @property
    def get_short_meeting_topic(self):
        if len(str(self.topic)) > 24:
            return f"{self.topic[:20]} ..."
        else:
            return self.topic

    @property
    def is_today(self):
        if self.start.date() == datetime.today().date():
            return True
        print("not today:", self.start)
        return False

    @property
    def is_expired(self):
        if get_naive_dt(datetime.utcnow()).date() > get_naive_dt(self._start).date():
            return True


"""
=================================
    QUIZZES
=================================
"""


class Quiz(models.Model):
    classroom = models.ForeignKey(Classroom, on_delete=models.CASCADE)
    owner = models.ForeignKey(Lecturer, on_delete=models.CASCADE)
    title = models.CharField(max_length=300)
    description = models.TextField(null=True, blank=True)
    _date_created = models.DateTimeField(auto_now_add=True)
    _date_modified = models.DateTimeField(auto_now=True)
    _start = models.DateTimeField()
    duration = models.IntegerField()
    accept_after_expired = models.BooleanField(default=True)

    class Meta:
        unique_together = (('classroom', 'title'),)

    def __str__(self):
        return f"Quiz: {self.title}"

    @property
    def type(self):
        return 'quiz'

    @property
    def date_created(self):
        return utc_to_local_naive(self._date_created)

    @property
    def date_modified(self):
        return utc_to_local_naive(self._date_modified)

    @property
    def live(self):
        if self.start < datetime.now() < self.end:
            return True
        return False

    @property
    def expired(self):
        if datetime.now() > self.end:
            return True
        return False

    @property
    def start(self):
        return utc_to_local_naive(self._start)

    @property
    def end(self):
        return self.start + timedelta(minutes=float(self.duration))


class QuizQuestion(models.Model):
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)
    number = models.PositiveIntegerField()
    question = models.TextField(default="")

    def __str__(self):
        return f"Question: {self.question} -> [<Quiz: {self.quiz.title}>]"

    @property
    def correct_answers(self):
        return self.answer_set.filter(correct=True)

    @property
    def incorrect_answers(self):
        return self.answer_set.filter(correct=False)


LETTER_CHOICES = [
    ('A', 'A'),
    ('B', 'B'),
    ('C', 'C'),
    ('D', 'D'),
    ('E', 'E'),
    ('F', 'F'),
]


class QuizQuestionAnswer(models.Model):
    question = models.ForeignKey(QuizQuestion, on_delete=models.CASCADE)
    letter = models.CharField(max_length=1, choices=LETTER_CHOICES)
    answer = models.CharField(max_length=300, default="")
    correct = models.BooleanField(default=False)    # Whether answer is a correct or incorrect

    def __str__(self):
        return f"Answer: {self.answer} -> " \
               f"[<Quiz: {self.question.quiz.title}> -> " \
               f"<Question: {self.question.question}>]"

    @property
    def get_q_id(self):
        id_map = {'A': 1, 'B': 2, 'C': 3, 'D': 4, 'E': 5, 'F': 6}
        return id_map.get(str(self.letter))


class QuizStudentResponse(models.Model):
    """
    One single student response made by a student.
    """
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)
    owner = models.ForeignKey(Student, on_delete=models.CASCADE)
    _date_created = models.DateTimeField(auto_now_add=True)
    score = models.FloatField(default=0)

    def __str__(self):
        return f"Quiz Response by: {self.owner.user.get_full_name()}"

    @property
    def date_created(self):
        return utc_to_local_naive(self._date_created)


class QuizStudentResponseQuestion(models.Model):
    """
    <QuizStudentResponse> related.

    ONLY RELATED TO A ONE SINGLE <QuizStudentResponse> MADE BY A STUDENT.
    Do not use for anything else.
    """

classrooms/templates/classrooms/class-create.html
{% extends 'main/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="container-fluid">
        <div class="container text-muted mt-5 mb-5 mw-700 p-sm-4 p-3 p-md-4 p-lg-5 background-light rounded shadow-sm">
            <form method="POST" class="mb-2" enctype="multipart/form-data">
                {% csrf_token %}
                <h4 class="mb-5 pb-2 border-bottom sm-heading-2 roboto-title-muted">
                    Create New Classroom
                </h4>

                {{ form|crispy }}
                <button type="submit" class="btn btn-primary mt-4 shadow">Create Classroom</button>
            </form>
        </div>
    </div>
{% endblock %}

classrooms/templates/classrooms/class-delete.html
{% extends 'main/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="container text-muted mt-5 mb-5">
        <div class="card">
            <div class="card-body">
                <form method="POST" class="mb-4 mt-3">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <h5 class="roboto-title-muted">Sure you want to delete this classroom ?</h5>
                    <h6 class="card-text roboto-title-muted mt-4">
                        <a href="{% url 'class-details' pk=classroom.pk %}">
                            {{ classroom.name }} ({{ classroom.department.batch.year }} Batch)
                        </a>
                    </h6>

                    <div class="class-info mt-4 mb-5">
                        <table class="table table-striped mw-300 text-muted">
                            <tr>
                                <th>Assignments</th>
                                <th>{{ classroom.assignment_set.count }}</th>
                            </tr>
                            <tr>
                                <th>Posts</th>
                                <th>{{ classroom.post_set.count }}</th>
                            </tr>
                            <tr>
                                <th>Quizzes</th>
                                <th>{{ classroom.quiz_set.count }}</th>
                            </tr>
                            <tr>
                                <th>Meetings</th>
                                <th>{{ classroom.meeting_set.count }}</th>
                            </tr>
                        </table>
                    </div>

                    <a href="{% url 'class-details' pk=classroom.pk %}" class="btn btn-secondary">Cancel</a>
                    <button type="submit" class="btn btn-danger ml-3">Yes, Delete</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

classrooms/templates/classrooms/class-detail.html
{% extends 'main/base.html' %}

{% block content %}
<div class="container-fluid p-0" xmlns="http://www.w3.org/1999/html">
        <div class="container mt-4 mb-5 min-body-height">
            <div class="card card-header mb-3 text-light bg-gradient-info class-detail-header bg-dark shadow mt-3">
                <div class="row">
                    <div class="col-12">
                        <div class="row">
                            <div class="col-10">
                                <h4 class="pl-3 pt-5 roboto-title">{{ class.name }}</h4>
                            </div>
                            <div class="col-2">
                                {% if class.owner == user.profile %}
                                    <a href="{% url 'class-update' class.pk %}" class="btn btn-light float-right shadow-sm">
                                        <i class="far fa-edit text-dark"></i>
                                    </a>
                                {% endif %}
                            </div>
                        </div>

                        {% if class.description %}
                            <p class="card-text pl-3 pt-3 pr-5 pb-3 mw-600">{{ class.description }}</p>
                        {% endif %}
                    </div>
                </div>
            </div><!-- .class-detail-header -->

            <ul class="nav nav-tabs mb-4 shadow-sm classroom-sub-nav" id="myTab" role="tablist"><!-- Stream, Classwork and People -->
                <li class="nav-item">
                    <a class="nav-link active" id="home-tab" data-toggle="tab" href="#stream" role="tab"
                       aria-controls="stream" aria-selected="true">Stream</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" id="profile-tab" data-toggle="tab" href="#classwork" role="tab"
                       aria-controls="classwork" aria-selected="false">Classwork</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" id="contact-tab" data-toggle="tab" href="#people" role="tab"
                       aria-controls="people" aria-selected="false">People</a>
                </li>
            </ul><!-- End of Stream, Classwork and People -->

            <!-- Nav Tabs for class details -->
            <div class="row text-muted">
                <div class="col-lg-8 col-md-12 mb-5 tab-content">
                    <div class="tab-pane fade show active" id="stream" role="tabpanel" aria-labelledby="pills-home-tab"><!-- stream -->

                        {% if user.role == 'lecturer' %}
                            <a href="{% url 'post-new' class.pk %}" class="card p-3 pl-4 mb-5 shadow-sm">
                                Announce something to your class
                            </a>
                        {% endif %}

                        {% for post in posts %} <!--Class posts goes here-->
                            {% include 'template-parts/class-post-item.html' %}
                        {% empty %}
                            <h4 class="text-center d-block w-100 mb-5 roboto-title-muted" style="margin-top: 100px;">
                                No Posts Yet
                            </h4>
                        {% endfor %} <!-- end of class posts -->

                    </div><!-- stream -->

                    <div class="tab-pane fade" id="classwork" role="tabpanel" aria-labelledby="pills-home-tab"><!-- classwork -->
                        <div class="mb-5">

                            <!--  Assignment and Quiz Create buttons -->
                            {% if user.role == 'lecturer' %}
                                <div class="row">
                                    <div class="col-12">
                                        <a class="btn btn-outline-secondary" href="#" role="button"
                                           data-toggle="dropdown" id="createNewDropdown">
                                            Add New<i class="fas fa-plus pl-3 font-weight-bold"></i>
                                        </a>

                                        <div class="dropdown-menu dropdown-menu-bottom"
                                             aria-labelledby="createNewDropdown" aria-expanded="false">
                                            <a class="dropdown-item"
                                               href="{% url 'assignment-new' class_pk=class.pk %}">Assignment
                                            </a>
                                            <a class="dropdown-item"
                                               href="{% url 'quiz-create' pk=class.pk %}">Quiz
                                            </a>
                                            <a class="dropdown-item" href="{% url 'meeting-create' pk=class.pk %}">Meeting</a>
                                        </div>
                                    </div>
                                </div>
                            {% endif %}

                        </div>
                        {% for work in class_work %}
                            {% if work.type == 'assignment' %}
                                {% include 'template-parts/class-assignment-item.html' %}
                            {% elif work.type == 'quiz' %}
                                {% include 'template-parts/class-quiz-item.html' %}
                            {% elif work.type == 'meeting' %}
                                {% include 'template-parts/class-meeting-item.html' %}
                            {% endif %}
                        {% empty %}
                            <h4 class="text-center d-block w-100 mb-5 roboto-title-muted" style="margin-top: 100px;">
                                No Assignments
                            </h4>
                        {% endfor %}
                    </div><!-- classwork -->

                    <div class="tab-pane fade" id="people" role="tabpanel" aria-labelledby="pills-home-tab"><!-- people -->
                        <div class="lecturers mb-2 mt-3">
                            <h4 class="roboto-title mb-3 pt-2 pb-2 pr-4">Lecturers</h4>
                            <div class="card-columns row">
                                {% for lecturer in lecturers %}
                                    {% include 'users/template-parts/user.html' with profile=lecturer %}
                                {% endfor %}
                            </div>
                        </div>
                        <div class="students mb-5">
                            <h4 class="roboto-title mb-3 pt-2 pb-2 pr-4">Students</h4>
                            <div class="card-columns row">
                                {% for student in students %}
                                    {% include 'users/template-parts/user.html' with profile=student %}
                                {% endfor %}
                            </div>
                        </div>
                    </div><!-- people -->
                </div>

                <!-- classroom right sidebar (recent activities) -->
                <div class="col-lg-4 col-md-12 pl-4 class-sidebar">
                    <div class="card border-0 pt-4 shadow-sm">
                        <div class="card-body text-center">
                            <h6 class="roboto-title">Posts</h6>
                            <h4 class="mb-4 font-weight-bold">{{ class.post_set.all.count }}</h4></br>

                            <h6 class="roboto-title">Assignments</h6>
                            <h4 class="mb-4 font-weight-bold">{{ class.assignment_set.all.count }}</h4></br>

                            <h6 class="roboto-title">Quizzes</h6>
                            <h4 class="mb-4 font-weight-bold">{{ class.quiz_set.all.count }}</h4>
                        </div>
                    </div>
                </div><!-- col -->

            </div><!-- row -->
        </div><!-- container -->
    </div><!-- container-fluid -->
{% endblock %}

classrooms/templates/classrooms/class-list.html
{% extends 'main/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="col-12 text-right pb-4 mt-4"> <!-- Model Trigger item-->
        {% if user.role == 'lecturer' %}
            <a href="{% url 'class-create' %}" class="btn btn-outline-primary shadow-sm">New Classroom</a>
        {% endif %}
    </div>

    <div class="container mt-3 mb-5 p-4 min-body-height">
        <div class="card-columns row">
            {% for classroom in class_rooms  %}
                <div class="card testimonial-card list-card mt-2 m-3">
                    <div class="card-up bg-gradient-info text-right">
                        {% if classroom.owner == user.profile %}
                            <i class="fa-solid fa-ellipsis-vertical fa-lg text-light p-3 pt-4 pb-4"
                               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></i>
                            <div class="dropdown-menu dropdown-menu-right"><!-- dropdown menu for edit and delete-->
                                <a href="{% url 'class-update' classroom.pk %}" class="dropdown-item">
                                    <i class="fas fa-edit pr-4 text-primary"></i>Edit</a>
                                <a href="{% url 'class-delete' classroom.pk %}" class="dropdown-item">
                                    <i class="fas fa-trash-alt pr-4 text-danger"></i>Delete</a>
                            </div>
                        {% endif %}
                    </div>
                    <div class="avatar mx-auto white">
                        <img src="{{ classroom.owner.profile_pic.url }}"
                             class="rounded-circle img-fluid" alt="woman avatar">
                    </div>
                    <div class="card-body text-center pt-1 text-muted">
                        <h6 class="font-weight-bold mb-0" style="font-size: 1.1rem;">
                            <a href="{% url 'class-details' classroom.pk %}"
                               class="class-name">{{ classroom.name }}</a>
                        </h6>

                        {% if user.role == 'lecturer' %}
                            <small class="pb-3 pt-1 m-0 d-block">
                                Owner:
                                {% if classroom.owner == user.profile %}
                                    Me
                                {% else %}
                                    {{ classroom.owner.user.get_full_name }}
                                {% endif %}
                            </small>
                            <a class="btn btn-info text-light font-weight-bold shadow-sm">
                                {{ classroom.department.batch.year|add:" Batch" }}</a>
                            <hr><p class="m-0">{{ classroom.department.name }}</p>

                        {% elif user.role == 'student' %}
                            <p class="pb-3 pt-1 m-0">
                                By: {{ classroom.owner.user.get_full_name }}
                            </p>
                            {% if classroom.description %}<hr>{{ classroom.description }}{% endif %}
                        {% endif %}
                    </div>
                </div>
            {% empty %}
                <h3 class="roboto-title-muted ml-auto mr-auto" style="margin-top: 150px;">
                    No Classrooms Yet
                </h3>
            {% endfor %}
        </div><!-- .card-columns -->
    </div><!-- .container -->
{% endblock %}

classrooms/templates/classrooms/class-update.html
{% extends 'main/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="container-fluid">

        <!-- Edit and delete options for publisher -->
        <div class="row post-author mw-700 ml-auto mr-auto mb-3 mt-5">
            <div class="col-8 text-left">
                <a href="{% url 'class-details' classroom.pk %}" class="text-left">
                    <i class="fas fa-long-arrow-left pr-2"></i>Back to Classroom
                </a>
            </div>
            <div class="col-4 text-right">
                <a href="{% url 'class-delete' pk=classroom.pk %}">
                    <i class="fas fa-trash-alt ml-3 text-danger"></i>
                </a>
            </div>
        </div>

        <div class="container text-muted mt-3 mb-5 mw-700 p-3 p-md-4 p-lg-5 background-light rounded shadow-sm">
            <form method="POST" class="mb-2" enctype="multipart/form-data">
                {% csrf_token %}
                <h4 class="mb-5 pb-2 sm-heading-2 roboto-title-muted border-bottom">
                    Edit:
                    <a href="{% url 'class-details' classroom.pk %}">
                        {{ classroom.name }}
                    </a>
                </h4>

                {{ form|crispy }}
                <button type="submit" class="btn btn-primary pl-3 pr-3 mt-4 shadow mobile-100">
                    Update Classroom
                </button>
            </form>
        </div><!-- .container -->
    </div>
{% endblock %}